version: '3.2'

services:
  mailtoolkit:
    build: ./app
    restart: always
    volumes:
    - /data/mail:/mail
    ports:
    - target: 8080
      published: 80
      protocol: tcp
      mode: host
    - target: 443
      published: 443
      protocol: tcp
      mode: host
  postfix:
    build: ./postfix
    restart: always
    volumes:
    - /data/mail:/var/mail
    ports:
    - target: 25
      published: 25
      protocol: tcp
      mode: host
    - target: 587
      published: 587
      protocol: tcp
      mode: host
    - target: 465
      published: 465
      protocol: tcp
      mode: host
volumes:
  mail:
